baseURL = "https://pelicanlife.dev/"
theme = "hextra"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
timeZone = "Asia/Seoul"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[services.googleAnalytics]
ID = "G-ER2MB6C294"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[languages]
  [languages.ko]
    languageName = "한국어"
    label = "한국어"
    locale = "ko"
    weight = 1
    title = "인생은 펠리컨처럼!"
    [languages.ko.menus]
      [[languages.ko.menus.main]]
        identifier = "blog"
        name = "블로그"
        pageRef = "/blog"
        weight = 1
      [[languages.ko.menus.main]]
        identifier = "about"
        name = "소개"
        pageRef = "/about"
        weight = 2
      [[languages.ko.menus.main]]
        identifier = "search"
        name = "검색"
        weight = 3
        [languages.ko.menus.main.params]
          type = "search"
      [[languages.ko.menus.main]]
        identifier = "lang"
        weight = 4
        [languages.ko.menus.main.params]
          type = "language-switch"

  [languages.en]
    languageName = "English"
    label = "English"
    locale = "en"
    weight = 2
    title = "Live Like a Pelican!"
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "blog"
        name = "Blog"
        pageRef = "/blog"
        weight = 1
      [[languages.en.menus.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 2
      [[languages.en.menus.main]]
        identifier = "search"
        name = "Search"
        weight = 3
        [languages.en.menus.main.params]
          type = "search"
      [[languages.en.menus.main]]
        identifier = "lang"
        weight = 4
        [languages.en.menus.main.params]
          type = "language-switch"

[params.navbar]
displayTitle = true
displayLogo = false

[params.page]
width = "normal"

[params.theme]
default = "system"
displayToggle = true

[params.footer]
enable = true
displayCopyright = true
displayPoweredBy = true
width = "normal"

[params.search]
enable = true
type = "flexsearch"
[params.search.flexsearch]
index = "content"
tokenize = "forward"

[params.blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"

[params]
displayUpdatedDate = true
dateFormat = "2006-01-02"
